#!/bin/bash
git pull
git reset --hard origin/master
npm install
npm run build
cd /etc/systemd/system
ln -f /opt/web-performance-monitor/systemd.service web-performance-monitor.service
systemctl enable web-performance-monitor
systemctl start web-performance-monitor